In [56]:
import numpy as np
from matplotlib import pyplot as plt
import tensorflow as tf

from vedo import *
from ipyvtklink.viewer import ViewInteractiveWidget
import nbconvert

%autosave 90

Autosaving every 90 seconds


In [57]:
# #limit GPU memory ------------------------------------------------
# gpus = tf.config.experimental.list_physical_devices('GPU')
# print(gpus)
# if gpus:
#   try:
#     memlim = 8*1024
#     tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=memlim)])
#   except RuntimeError as e:
#     print(e)
# #-----------------------------------------------------------------

In [58]:
A = np.random.randn(1_000,3)
print(A)
# B = tf.random.normal([10_000_000])

[[-0.32701921  1.85725612 -1.0392801 ]
 [-0.38216057  0.19564436  0.30139398]
 [ 1.44413489 -1.1047982   0.77048724]
 ...
 [-0.77254479 -0.52042495 -1.02080286]
 [ 0.27210535  0.57551344  1.85894387]
 [-1.82321168  1.15079993 -0.08130741]]


In [59]:
# fig, ax = plt.subplots()
# ax.scatter(A)

In [61]:
plt = Plotter(N=1, axes=1, bg=(1,1,1), interactive = True)
disp = []

disp.append(Points(A, c = 'blue', r = 2))

plt.show(disp, "test")
ViewInteractiveWidget(plt.window)

TypeError: cannot create weak reference to 'NoneType' object